apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: tikky-app
  labels:
    app: redis
spec:
  # NOTE: we need to exclude the cluster IP to make this headless
  clusterIP: None
  ports:
    - port: 6379
      targetPort: 6379
      name: redis
  selector:
    app: redis