apiVersion: v1
kind: Service
metadata:
  name: tikky-api-service
  namespace: tikky-app
  labels:
    app.kubernetes.io/name: tikky-api
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: tikky-api